# Generated by Django 3.1.7 on 2021-03-11 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210311_2358'),
        ('spot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='latitude',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='longitude',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='users.user'),
        ),
    ]
